services:
  postgres:
    image: postgres:15.4
    container_name: postgres_conteiner
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin

  tree_menu:
    image: tree_menu:1
    container_name: tree_menu_conteiner
    ports: 
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - DATABASE_HOST=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
      - POSTGRES_DB=django_tree_menu